name = "ItuRPropagations"
uuid = "27e0793c-dcf3-4b51-9682-e1c9838db8f8"

authors = ["Hillary Kchao <hillary.kchao@gmail.com>"]
version = "0.1.0"
repo = "https://github.com/HillaryKchao/ItuRPropagations"

[compat]
julia = "1.8.2"