name = "ItuRPropagations"
uuid = "27e0793c-dcf3-4b51-9682-e1c9838db8f8"
authors = ["Hillary Kchao <hillary.kchao@gmail.com>"]
repo = "https://github.com/HillaryKchao/ItuRPropagations"
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.8.2"
